---
abstract: 'Helper functions for Taiwan Futures Exchange'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-TW-TAIFEX
no_index:
  directory:
    - inc
    - share
    - t
    - xt
recommends:
  MooseX::Traits: 0
  MooseX::Types::DateTime: 0
requires:
  Any::Moose: 0.04
  DateTime: 0
  File::ShareDir: 0
  HTTP::Request::Common: 0
  List::MoreUtils: 0
  MouseX::NativeTraits: 0
  MouseX::Traits: 0
  MouseX::Types::DateTime: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.tradroom.com/lib/Finance-TW-TAIFEX
version: 0.34
